# -*- coding: utf-8 -*-
"""Day 3_Multilinear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xQOON1iQ2_g0OtyGJZKJ4hfUvowMEU2

Importing the libraries
"""

import pandas as pd
import numpy as np

"""Importing the dataset"""

dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[ : , :-1].values
Y = dataset.iloc[ : ,  4 ].values

"""Encoding Categorical data"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer


# Create a ColumnTransformer to apply OneHotEncoder to the specific column
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [3])],  # Apply OneHotEncoder to column index 3
    remainder='passthrough'  # Keep other columns unchanged
)

# Fit and transform the data
X = ct.fit_transform(X)

"""Avoiding Dummy Variable Trap"""

X = X[: , 1:]

"""Splitting the dataset into the Training set and Test set"""

# Instead of:
# from sklearn.model_validation import train_test_split

# Use:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

"""Step 2: Fitting Multiple Linear Regression to the Training set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

"""Step 3: Predicting the Test set results"""

y_pred = regressor.predict(X_test)

# Display the predicted values
print("Predicted values:", y_pred)